@startuml
Document --  Author: Contains
Document -- Title: Contains
LibraryManager --  Document: Manages
App ..> LibraryManager : creates

class Title {
        - static contadorIds: int = 0
        - id: int
        - name: String

        + Title(name: String)
        + getId(): int
        + getName(): String
    }

class Author {
        - static contadorIds: int = 0
        - id: int
        - name: String

        + Author(name: String)
        + getId(): int
        + getName(): String
    }

class Document {
        - static contadorIds: int = 0
        - id: int
        - title: Title
        - type: String
        - language: String
        - authors: Author[]
        - keywords: String[]
        - publishYear: String

        + Document(title: Title, type: String, language: String, publishYear: String)
        + getId(): int
        + getTitle(): Title
        + getType(): String
        + getLanguage(): String
        + getAuthors(): Author[]
        + setAuthors(authors: Author[])
        + setKeywords(keywords: String[])
        + getKeywords(): String[]
        + getPublishYear(): String
    }

class LibraryManager {
        - documents: List<Document>

        - LibraryManager()
        - addDocument(document: Document): void
        - searchDocument(criterio: String, valor: String): List<Document>
        - mostrarDocumentos(documents: List<Document>): void
        - addDocument(): void
        - searchOption(): void
        + startLibraryManager(): void
    }

class App {
        + main(args: String[]): void
    }
@enduml