@startuml class diagram

hide empty methods
hide empty attributes

class DocumentManager{
  - ArrayList<Author> authors
  - ArrayList<Document> documents
  - ArrayList<Relation> relations

  + DocumentManager()
  + void start()
  - ArrayList<Author> getAllAuthors()
  - ArrayList<Document> getAllDocuments()
  - ArrayList<Author> getAuthorsByBookId(int id)
  - ArrayList<Document> getDocumentsByAuthorId(int id)
  - Author getAuthorById(int id)
  - Document getDocumentById(int id)
  - void createDocument()
  - void editDocument()
  - void deleteDocument()
  - void createAuthor()
  - void editAuthor()
  - void deleteAuthor()
  - void createRelation()
  - void updateRelation()
  - void deleteRelation()
  - void filterDocuments()
}

class Document{
  - int id
  - String title
  - DocumentTypes type
  - String releaseDate
  - ArrayList<String> keyWords
  + Document()
  + int getId()
  + String toString()
}

class ArrayList{}

class Author{
  - int id
  - String name
  + Author()
  + int getId()
  + String getName()
  + String toString()

}

class Relation{
  - int authorId
  - int documentId
  + Relation()
  + int getAuthorId()
  + int getDocumentId()
}

enum DocumentTypes{
  Book
  Magazine
  Article
  Scientific_Paper
}

DocumentManager -down- Relation
Author "1" -right- "0..*" Relation
Document "1" -left- "1..*" Relation
DocumentManager .right. ArrayList : uses
Document -- DocumentTypes
@enduml