@startuml class diagram

hide empty methods
hide empty attributes

class ArrayList{}

class LibraryManager{
  - ArrayList<Author> authors
  - ArrayList<Document> documents
  - ArrayList<Relation> relations
  - Scanner scanner

  + DocumentManager()
  + void start()
  - ArrayList<Author> getAllAuthors()
  - ArrayList<Document> getAllDocuments()
  - ArrayList<Author> getAuthorsByBookId(int id)
  - ArrayList<Document> getDocumentsByAuthorId(int id)
  - Author getAuthorById(int id)
  - Document getDocumentById(int id)
  - void deleteDocument()
  - void deleteAuthor()
  - void deleteRelation()
  - void filterDocuments()
}

class LibraryGenerator{
  - Scanner scanner
  + void createDocument()
  + void createAuthor()
  + void createRelation()
}

class LibraryEditor{
  - Scanner scanner
  + void editAuthor()
  + void editDocument()
  + void updateRelation()
}

class Document{
  - int id
  - String title
  - DocumentTypes type
  - String releaseDate
  - ArrayList<String> keyWords
  + Document()
  + int getId()
  + String toString()
}

class Author{
  - int id
  - String name
  + Author()
  + int getId()
  + String getName()
  + String toString()

}

class Relation{
  - int authorId
  - int documentId
  + Relation()
  + int getAuthorId()
  + int getDocumentId()
}

enum DocumentTypes{
  Book
  Magazine
  Article
  Scientific_Paper

  + getType()
  + getAllTypes()
}

LibraryManager -- LibraryGenerator : uses
LibraryManager -- LibraryEditor : uses
LibraryManager -- Relation : manage
LibraryManager -- ArrayList : uses
Relation -- "1..*" Author : contains
Relation -- "1..*" Document : contains
Document -- DocumentTypes : has
@enduml